# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.1
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Escodoo
org_slug: Escodoo
rebel_module_groups: []
repo_description: Purchase Odoo Addons
repo_name: Purchase Odoo Addons
repo_slug: purchase-addons
repo_website: https://github.com/Escodoo/purchase-addons

